# Generated by Django 3.0.8 on 2020-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('img', models.BinaryField(verbose_name='画像')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
